### ISSUE TITLE
plugins: component mounts again on switching editing mode

### ISSUE THREAD

**Issue by Knorrke** [aeneasr/ory-editor#293]
Components mount again each time one switches between editing and layout (add, rearrange, resize) mode.

**Comment by arekkas** [comment]
why is that a problem?

**Comment by Knorrke** [comment]
I'm currently working on an injection plugin and this causes a new request to the injected Element each time you switch the mode.

**Comment by arekkas** [comment]
I see, you could probably abstract the http call away and put some caching in place, or use the state to store the data temporarily

**Comment by Knorrke** [comment]
So, you mean the global editor store? Because storing the data in the component (which I tried) doesn't work, as it looses the state on mounting, or does it?

**Comment by arekkas** [comment]
Yes you are correct. We sort of use the global store for storing temporary data from slate and use unserialize/deserialize to clean it up when exporting or hydrate it when importing. It would be, of course, better if there was no need for it, but I'm not sure if there is a quick fix for this issue.

Maybe opt for a `MyPluginService` for now that does some caching.

@inyono your opinion is valuable here :)

**Comment by inyono** [comment]
I basically said the same thing. Furthermore, if done correctly, we might get a better UX when storing the response in state since we can already show the exercise before making the request (especially annoying when having bad network connection). Similar to server-side rendering

**Comment by arekkas** [comment]
Yes that is true. However, I dislike that deserialize and serialize might become such a popular use case. It's very easy to mess up here and return an invalid state as a third party developer. This might break the cell's content as a whole.

Do we have any other way of solving this?

**Comment by inyono** [comment]
Not sure what this has to do with (de-)serialize?

**Comment by arekkas** [comment]
because it's cleaning the state up? or do you want to store the cache data within the document?

**Comment by inyono** [comment]
Yep, I wanted to store it within the document.

**Comment by Knorrke** [comment]
Solved this with a global cache, which is a good enough solution for me. Thanks 👍 -> Closing
