### ISSUE TITLE
Exporting HTML

### ISSUE THREAD

**Issue by kartboy16** [aeneasr/ory-editor#507]
Awesome work!!

Just trying to export the HTML but when I tried `https://github.com/ory/editor/blob/master/docs/walkthrough/exporting-html.md` 
I get the following error: 

`editor.renderToHtml is not a function
`

Is there an export function on the HTMLRenderer?

**Comment by arekkas** [comment]
Oh, that has been changed. Here's the working version: https://github.com/ory/editor/blob/master/examples/src/index.js#L105

**Comment by kartboy16** [comment]
Thanks @arekkas!  Keep up the great work!

**Comment by bekicot** [comment]
The permanent link to the example mentioned by @aeneasr 

https://github.com/ory/editor/blob/db2f1774176625eaef61214f5f5e24cc90800701/examples/src/index.js#L105

**Comment by davidfurlong** [comment]
this issue can probably be closed?

**Comment by aeneasr** [comment]
yup

**Comment by hoseyneil** [comment]
Im struggling to understant how I would use this to output HTML?  Can you point me in a direction here?

I'd like to do it on the server side in a node app... but cannot figure out how, any suggestions?
