### ISSUE TITLE
Create Plugins Documentations for `text` Editor

### ISSUE THREAD

**Issue by mohamednizar** [aeneasr/ory-editor#610]
I'm working with ory editor, it has bunch of features. I needs to develop plugins which  are need to render inside the text editor like link. This plugins are  using for letter templates , some thing like Name, salary, Employee No. 

Currently I have developed , but they are rendering as individual components and cell. 

How can I get done this?

**Comment by davidfurlong** [comment]
I'm finding it hard to understand what you're asking, perhaps if you post some of the code I can better understand :)

**Comment by aeneasr** [comment]
Also inactive for a while -> closing :)
