### ISSUE TITLE
[Feat request] Ability to use existing redux store

### ISSUE THREAD

**Issue by davidfurlong** [aeneasr/ory-editor#611]
We use redux in our project too, and unfortunately this means that both redux stores have the same `storeKey` (see https://github.com/reduxjs/react-redux/blob/master/docs/api.md#arguments). This means that our widgets which try to `connect` to our store from inside `ory-editor` can't connect, as the `storeKey` is the same. We have renamed our `storeKey`, but unfortunately many popular `redux` libraries such as `redux-form` don't currently support passing a custom `storeKey` (other than 'store'). 

I understand that `redux` is used internally by `ory-editor` and that you probably don't want it to be a `peerDependency`, but ideally 

a) you use a different `storeKey` internally in this project, to avoid namespace collisions with implementers
b) its possible to use this library with an existing redux `store` under a specific key (the way many redux-based libraries handle this case)

Thanks for reading!

**Comment by aeneasr** [comment]
Yeah, that definitely makes sense!

**Comment by davidfurlong** [comment]
> Yeah, that definitely makes sense!

Any opinions on which solution would be preferred?

**Comment by aeneasr** [comment]
I think it should be possible to override the store in the `Editor` class, given that both middlewares and redux stores are properly set. You could probably try doing something like this already to prototype it:

```
const store =  // createStore()
const e = new Editor()
e.store = store

...

React.render(<Editable ...)
```

**Comment by davidfurlong** [comment]
Cool this is merged :)
