### ISSUE TITLE
How can I get non-obfuscated javascript and css files?

### ISSUE THREAD

**Issue by sahadith** [aeneasr/ory-editor#620]
Hello.
When compiling a project with commands:
```
$ yarn run build
$ cd examples
$ yarn run start
```

All files in the \ editor \ examples \ build \ static \ 
javascript and css folder are obfuscated.
How can I get non-obfuscated javascript and css files?

This is necessary to connect them to the head of the page via 
`<link href = "... and <script type =" text / javascript "src =" ...`

For example, the same two files main.xxxxxxxx.js and main.xxxxxxxx.css but not obfuscated?
Thank.

**Comment by davidfurlong** [comment]
Do you mean without hashed file names? 

The hashing is done to bust caches, but if for some reason you want the example build without these, you can look here: `https://www.npmjs.com/package/react-scripts` which is used to build the examples
