### ISSUE TITLE
Decouple from React and Redux

### ISSUE THREAD

**Issue by EisenbergEffect** [aeneasr/ory-editor#631]
Nifty editor you've got here. I'd like to use it, but unfortunately I can't take a dependency on React or Redux. It would be great if Ory was framework-agnostic and built with VanillaJS. Has there been much consideration into making this change? How coupled is the core to React/Redux? Is it just a matter of writing a thin layer on top of an editor "backend" or are things coupled at the core?

**Comment by aeneasr** [comment]
No, it is not possible to build this type of technology without React nor Redux, unless you want to reinvent those two exact technologies again.

**Comment by EisenbergEffect** [comment]
I know that's not true. But, I'll just interpret this as there being no intention to try. Thank you for your prompt response.
