### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tebriz159** [aeneasr/ory-editor#635]
Hello , I just saw your project, the project has over 7k stars congrats to you. I'm a logo designer and I want to contribute on your project. I can make a free logo for your project if you want.

**Comment by aeneasr** [comment]
That's really nice of you! I'd be happy to see what you come up with, but I can't make guarantees that it will become the official logo :)

**Comment by tebriz159** [comment]
Sure, I have some design works but after I'm done I will design logo for your project.

**Comment by tebriz159** [comment]
Hi, I made a logo and I couldn't decide which color do you want. So, I made color variations of the logo. If you want to use it I'll send you the original files about the logo.
![ory pr2](https://user-images.githubusercontent.com/31902754/51708243-40ad3180-1fd8-11e9-8e28-81ec3c08aca1.png)

Which color do you prefer?

![ory pr](https://user-images.githubusercontent.com/31902754/51708379-a7324f80-1fd8-11e9-8163-a0a25438756d.png)

**Comment by alexstandiford** [comment]
Ooh! I like this.

**Comment by aeneasr** [comment]
This is awesome :) I like the blue one!

**Comment by tebriz159** [comment]
I'm glad that you like it, please let me know after you implement the logo. All files about the logo is here: https://drive.google.com/open?id=19oONh4rHPqiIPlRtwYig5uG1wlAvrBET

**Comment by aeneasr** [comment]
Awesome! Under which license would you provide this logo? One example could be one of the Creative Common licenses: https://creativecommons.org/

This is important for this repo as I'll be adding the logo to the repository itself so this has to be clear :)

**Comment by tebriz159** [comment]
Doesn't matter for me, use which you want. I'm a utopian contributor and I always use Creative Common license when I share my work.

**Comment by aeneasr** [comment]
Thank you Tebriz! Sorry for taking a bit of time for this but the logo is now in the readme and I've linked your GH profile in the readme too :) LMK if you want a link to your website there or whatever.

**Comment by tebriz159** [comment]
Looks great, thank you for adding my GH profile. And LMK if you need a logo design for any project.

**Comment by aeneasr** [comment]
I will! Thank you :)
