### ISSUE TITLE
Push new versions to npm

### ISSUE THREAD

**Issue by fernandobandeira** [aeneasr/ory-editor#645]
@aeneasr Just a reminder to publish the new versions to npm, currently the latest version available is 0.6.0 while we're on 0.6.2 here on Github.

**Comment by aeneasr** [comment]
Yeah thanks, there is a problem with TS it seems. If you have a free minute I'd appreciate a PR!

https://travis-ci.org/aeneasr/ory-editor/jobs/489994543#L707
