### ISSUE TITLE
Layout plugin has no children

### ISSUE THREAD

**Issue by isvaljek** [aeneasr/ory-editor#653]
The updated Layout plugin tutorial works in that it creates an empty black border div, but has no children.
There should be Slate plugin as a first child.

**Comment by isvaljek** [comment]
Layout plugin added to content array, doh!

**Comment by muhajirdev** [comment]
Hi @isvaljek , I am facing the same problem. How did you solve this?

**Comment by isvaljek** [comment]
Hi, in my case the error I believe was in that I added a Layout plugin to the Content plugins array.

**Comment by muhajirdev** [comment]
Thanks @isvaljek
